#  ruby encoding: utf-8

Cuisine.create(name: 'Italian')
Cuisine.create(name: 'American')
Cuisine.create(name: 'Breakfast')
Cuisine.create(name: 'Chinese')
Cuisine.create(name: 'Sushi')
Cuisine.create(name: 'Ramen')
Cuisine.create(name: 'Indian')
Cuisine.create(name: 'Fast Food')
Cuisine.create(name: 'Thai')
Cuisine.create(name: 'Mexican')
Cuisine.create(name: 'Korean')
Cuisine.create(name: 'Vegetarian')
Cuisine.create(name: 'BBQ')
Cuisine.create(name: 'Mediterranean')
Cuisine.create(name: 'Dessert')
Cuisine.create(name: 'Coffee')
Cuisine.create(name: 'Pizza')
User.create(username: 'scott', password: ENV['ADMIN_PSW'], admin: true)